### ISSUE TITLE
Scoping Error

### ISSUE THREAD

**Issue by jevdplas** [acieroid/scala-am#10]
Currently, Scala-AM uses lexical addressing. However, when multiple variables with the same name are defined in the same scope, some variables are incorrectly resolved. This issue is visible when a primitive that is preluded, but the file contains a top-level definition with the same name. In this case, the primitive will be references, not the definition (which should shadow the primitive).

**Comment by noahvanes** [comment]
Not an issue: the lexical addresser already gives priority to the latest definition in the scope, and the described behaviour therefore could not be reproduced. However, to avoid confusion, the lexical addresser will now instead throw an error when we have duplicate definitions in the same scope, since this should preferably not be allowed.
